### PR TITLE
Chore: Initial Application Setup

### PR DESCRIPTION
**Pull request by KMaina**
#### What does this PR do?
Set up the application by installing the necessary frameworks and packages.
#### Description of Task to be completed?
- Install Django and Django Rest Framework
- Install and enable Flake8 linting
- Enable static type checking using mypy
- Enable code cleanup using black and isort
- Add a Makefile
#### How should this be manually tested?
- run `git pull && git fetch` to get the latest changes
- run `git checkout ch-initial-setup`
- run a migration and check if the tables were created in the database
- start the server to confirm the app was set up properly.

#### Any background context you want to provide?
N/A
#### What are the relevant Trello stories?
[Trello job card](https://trello.com/c/jiSqOLAZ/1-project-setup)
#### Screenshots (if appropriate)
N/A

### CODE REVIEW

**Comment by KMaina** [comment]
[Project setup](https://trello.com/c/jiSqOLAZ/1-project-setup)

**Comment by thuitafaith** [comment]
write some

**Comment by thuitafaith** [comment]
When I try to check out to the set up branch I get the following error `error: The following untracked working tree files would be overwritten by checkout:
	Pipfile
Please move or remove them before you switch branches.
Aborting
`

**Comment by KMaina** [comment]
> 
> 
> When I try to check out to the set up branch I get the following error `error: The following untracked working tree files would be overwritten by checkout: Pipfile Please move or remove them before you switch branches. Aborting `

This is probably because you have made changes on the branch you are working on but not committed them. Kindly check and see if this is so

**Comment by thuitafaith** [comment]
I have not worked on any of the branches, even after I git fetch I still have the development branch only

**Comment by thuitafaith** [comment]
Let me try cloning again

**Comment by thuitafaith** [comment]
It's good now cloned it again

**Comment by thuitafaith** [comment]
Looks good to me.Everything ran successfully.

**Review by thuitafaith — APPROVED** [review]

**Pull request merged**
